# GitHub Sponsors configuration
# Visit https://github.com/sponsors/sidinflorencers9903 to sponsor this project

github: [sidinflorencers9903]

# Sponsorship tiers available:
# 🌱 Supporter: $5/month - Help keep the scrapers running
# 🚀 Power User: $10/month - Priority feature requests + monthly updates
# 💎 Premium Sponsor: $25/month - 1-on-1 setup help + custom settlement alerts
